from menuWidget import MenuWidget
from seedlingsWidget import SeedlingsWidget
from greenhousesWidget import GreenhousesWidget
from getPlantingProgramWidget import GetPlantingProgramWidget
from getPickingProgramWidget import GetPickingProgramWidget